name: country_flags
description: A Flutter package to show a flag icon from a ISO country code.
version: 3.1.0
homepage: https://github.com/arturograu/country_flags
repository: https://github.com/arturograu/country_flags

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  jovial_svg: ^1.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  very_good_analysis: ">=5.0.0+1 <8.0.0"

flutter:
  assets:
    - res/si/
