name: country_flags
description: A Flutter package to show a flag icon from a ISO country code.
version: 2.1.0
homepage: https://github.com/arturograu/country_flags
repository: https://github.com/arturograu/country_flags

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  jovial_svg: ^1.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  assets:
    - res/si/

