name: country_flags
description: A Flutter package to show a flag icon from a ISO country code.
version: 1.0.0
homepage: https://github.com/arturograu/country_flags
repository: https://github.com/arturograu/country_flags

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - res/

